// <auto-generated />
using ItmoPhysics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItmoPhysics.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20231130233958_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebMatrixUploader.Data.DataForMatrix.Abscissa", b =>
                {
                    b.Property<int>("AbscissaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbscissaId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AbscissaId");

                    b.ToTable("Abscissa");
                });

            modelBuilder.Entity("WebMatrixUploader.Data.DataForMatrix.CurveData", b =>
                {
                    b.Property<int>("CurveDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurveDataId"));

                    b.Property<int>("AbscissaId")
                        .HasColumnType("int");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<int>("OrdinateId")
                        .HasColumnType("int");

                    b.HasKey("CurveDataId");

                    b.ToTable("CurveData");
                });

            modelBuilder.Entity("WebMatrixUploader.Data.DataForMatrix.Ordinate", b =>
                {
                    b.Property<int>("OrdinateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrdinateId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrdinateId");

                    b.ToTable("Ordinates");
                });

            modelBuilder.Entity("WebMatrixUploader.Data.DataForMatrix.UserFile", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"));

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileId");

                    b.ToTable("UsersFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
